### PR TITLE
Send auth credentials

### LINKED ISSUE #30: Send auth credentials
If you want to access prvt over the Internet, it makes sense to put an authentication such as the Basic HTTP auth in between. Currently, this does not work because this [line](https://github.com/ItalyPaleAle/prvt/blob/befe766b534e11c1a09f7c9ff20377375525e4bb/ui/src/shared/request.ts#L36) prevents credentials from being sent, which makes all fetch requests impossible

[mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials) & also [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials)

### PR DESCRIPTION
**Pull request by rasmuslos**
Closes #30

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
(Aside from the fact that I need to investigate the CI failing)

I would like to understand a bit more about your scenario. I put that line there on purpose because prvt was not designed to be used over a network, in fact it lacks authentication (by design) and TLS support. How would you like to use prvt?

**Comment by rasmuslos** [comment]
I think the error in the CI was introduced by the [dependabot](https://github.com/ItalyPaleAle/prvt/pull/29). My solution is not particularly intelligent, but it works ...

The go binary with which I manage a locale repo is installed on a Linux server. In order to keep the whole thing constantly online without using systemctl, because I hate systemctl, I put the binary in a Docker container, which has the repo as a mount on `/files`
```
prvt
  - prvt
  - Dockerfile
  - compose.yml
```
```                          
FROM golang:1.11-alpine

WORKDIR /prvt
COPY prvt prvt

EXPOSE 3129
VOLUME /files

ENTRYPOINT ./prvt serve --no-unlock --read-only --address 0.0.0.0 -s local:/files
```

Since I use a reverse proxy traefik I added a Basic HTTP Auth. The whole thing looks like this in the compose file:
```yml
version: '3'

services:
  prvt:
    container_name: prvt
    image: prvt
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.prvt.service=prvt
      - traefik.http.routers.prvt.rule=Host(`HOST`)
      - traefik.http.routers.prvt.middlewares=auth
      - traefik.http.services.prvt.loadbalancer.server.port=3129
    volumes:
      - /REPO:/files
networks:
  proxy:
    external: true
```
The authentication middleware is in a different file:
```
- traefik.http.middlewares.auth.basicauth.users=USER
```
If you now go to the domain you will receive the request to register from the browser. There you enter a username & password, which are encrypted and transmitted via https. The password is hashed in the traefik config. From this point on, everything behaves normally, i.e. you will be asked for the repo passphrase, etc.

I know that this is not an elegant solution and that the image & the container are not particularly nice but it works. The whole thing should only offer protection if the repo is not encrypted, i.e. if the passpharse is saved on the server after it has been entered. I could also just use the in-browser decryption, but since the go asm is missing and, to be honest, I have no idea about GO, only about JS, this solution made more sense to me ...

To come back to the real problem after an essay:
If you use basic HTTP authentication with prvt you get the index as usual. But since all fetch requests are sent with `credentials: "omit" `, the HTTP auth credentials are not sent to the server, which leads to a 401 error

**Comment by ItalyPaleAle** [comment]
Ok I'll merge this. To be fully honest, this is not a behavior I would like to incentivize because prvt was not designed to be used over a network. Ideally, once I get to finish the work on the in-browser e2e encryption, that would allow using remotely and still offer the needed safety.

But at least sounds like you "did your homework" and are aware of the risks and are handling this well.

PS: On your Dockerfile, I'd recommend using Go 1.15 at least!

**Comment by ItalyPaleAle** [comment]
Ok I'll merge this. To be fully honest, this is not a behavior I would like to incentivize because prvt was not designed to be used over a network. People adding authentication through reverse proxies *could* give users a false sense of security which they shouldn't rely on (you lose e2e encryption by being over a network!)

Ideally, once I get to finish the work on the in-browser e2e encryption, that would allow using remotely and still offer the needed safety.

But at least sounds like you "did your homework" and are aware of the risks and are handling this well.

PS: On your Dockerfile, I'd recommend using Go 1.15 at least!

**Comment by rasmuslos** [comment]
I will do that, Thanks 👍

**Pull request merged**
